"""Added profile_image column to user

Revision ID: 3f10bb21e119
Revises: 145bdffe65ec
Create Date: 2025-12-16 02:09:21.238674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f10bb21e119'
down_revision = '145bdffe65ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=150), nullable=True))
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.VARCHAR(length=6), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
